apiVersion: sqs.services.k8s.aws/v1alpha1
kind: Queue
metadata:
  name: demo-queue-ack
  namespace: default
spec:
  queueName: demo-queue-ack
  visibilityTimeout: 30
  messageRetentionPeriod: 345600
  delaySeconds: 0
---
# apiVersion: s3.services.k8s.aws/v1alpha1
# kind: Bucket
# metadata:
#   name: demo-ack-bucket-1337
# spec:
#   name: demo-ack-bucket-1337
#   acl: private
