apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  project: default
  source:
    repoURL: "https://github.com/albertsuwandhi/gitops.git"
    path: apps/demo-app
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true