apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: arn:aws:eks:ap-southeast-1:004722542845:cluster/eks-sandbox #https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: "https://github.com/albertsuwandhi/gitops.git"
    path: argocd-apps
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
